package exception;

public enum ErrorCodes {
    
    BASE_IO_ERROR(101),UNSUPPORTED_ENCODING_ERROR(102),UNSUPPORTED_PLAYLIST_ERROR(103),
    REFLECT_UNKNOWN_METHOD_ERROR(201),ILLEGAL_ACCESS_ERROR(202),ILLEGAL_ARGUMENT_ERROR(203),
    INVOCATION_TARGET_ERROR(204),NO_SUCH_FIELD_ERROR(205),SECURITY_ERROR(206),INSTANSTIATE_ERROR(207),
    AUDIOFILE_READING_ERROR(301),AUDIOFILE_IO_ERROR(302),AUDIOFILE_TAG_ERROR(303),READONLY_FILE_ERROR(304),
    INVALID_AUDIOFRAME_ERROR(305),KEYNOTFOUND_ERROR(306),INVALID_FIELDDATA_ERROR(307),CANNOTWRITE_ERROR(308),
    WEB_INTERRUPTED_ERROR(401),WEB_REFERENCE_PATH_NOTFOUND_ERROR(402);

    private int code;

    ErrorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }

}
